sudo: required # To use docker, we always need sudo permission
services:
  - docker # Add docker to our little running container

before_install: # Declares steps to do before running our tests or deploy our code.
  - docker build -t andydevstic/docker-react -f dockerfile.dev .

# steps to produce when preparation steps has been finished.
# Each step should exit automatically with success. If each step exits with exit code != 0 or just hangs then it's not what we want.
script:
  - docker run -e CI=true andydevstic/docker-react npm run test # -e flag is used to set environmental variables inside the docker-container.
